// Write a build stamp into src/build.js.
//
// Displayed in the corner of the page so what is on screen can be checked against
// what was last built — a stale cached module is otherwise indistinguishable from a
// change that did not work.
//
//   npm run stamp
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const now = new Date();
const pad = (/** @type {number} */ n) => String(n).padStart(2, '0');
const stamp =
  `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ` +
  `${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'build.js');

writeFileSync(
  out,
  `// @ts-check\n\n` +
    `// Generated by tools/stamp.mjs — do not edit by hand.\n` +
    `/** When this build was stamped, in local time. */\n` +
    `export const BUILD = '${stamp}';\n`,
);

console.log(stamp);
